In [5]:
from vit_pytorch import ViT
import timm

In [6]:
import torch
import torchvision

In [7]:
model_ft = timm.create_model('vit_base_patch16_224',pretrained = True)

In [8]:
x=torch.randn((1,3,224,224))

In [10]:
x.shape

torch.Size([1, 3, 224, 224])

In [11]:
model_ft(x)

tensor([[-4.0052e-01,  1.3426e+00,  1.3008e+00,  1.3613e+00,  2.2956e+00,
          2.0791e+00,  1.0564e+00,  1.0654e+00,  2.3276e-01,  6.4902e-01,
          1.2506e+00,  1.8922e+00,  2.3164e+00,  1.3700e+00,  2.3549e+00,
          1.8984e+00,  1.8491e+00, -2.3072e-01,  2.7219e+00,  4.4831e-01,
          7.6814e-01,  5.6488e+00,  3.9322e+00,  4.3506e+00,  3.1146e+00,
         -4.9811e-01,  9.4322e-02, -1.0321e+00, -6.1043e-01,  2.8763e-01,
          4.9213e-01,  1.3200e+00,  7.4146e-01,  5.6203e-01,  1.1494e+00,
         -6.3179e-01, -1.0408e+00, -1.6243e+00,  2.5613e-01, -5.0482e-01,
          1.9953e-01, -5.6820e-01, -4.4837e-01,  6.3074e-01, -1.5326e+00,
         -8.0120e-01, -4.8387e-01,  3.8029e-02, -1.5994e+00, -1.1482e+00,
          1.2432e-01,  6.0533e-01, -2.4450e-01,  3.9061e-02,  2.5504e-01,
         -1.3776e-02, -1.1741e+00, -8.8370e-01, -1.8994e-01,  2.1023e+00,
          5.0987e-01, -4.5092e-01, -1.0164e+00,  1.1866e+00,  7.3231e-01,
          7.6217e-01,  9.4108e-02, -2.

In [12]:
model_ft

VisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (blocks): Sequential(
    (0): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop): Dropout(p=0.0, inplace=False)
      )
    )
    (1): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn

In [14]:
torch.save(model_ft.state_dict(), '/home/uzair.khattak/ML_project/ml_project/saved_models/recylce_material512by512')

In [15]:
loaded=torch.load('/home/uzair.khattak/ML_project/ml_project/saved_models/recylce_material512by512')

In [16]:
loaded

OrderedDict([('cls_token',
              tensor([[[ 3.2389e-01,  1.4362e-02, -4.3632e-01, -2.9668e-02,  4.9954e-01,
                         3.4431e-01,  6.9270e-02,  1.5145e-02,  1.5875e-01,  6.6091e-03,
                         2.9595e-02,  2.6433e-02,  4.8807e-02,  1.5438e-01,  7.6776e-02,
                        -5.6193e-02,  2.3481e+00, -3.7596e-02, -7.9648e-02, -3.2865e-02,
                         4.0753e-02,  1.0625e-01,  1.2637e-02,  1.2623e-01, -5.1822e-03,
                        -2.3552e-01,  3.1639e-02,  6.2501e-02,  3.5712e-02, -1.7925e-02,
                        -2.7995e-02,  8.2622e-01,  5.4036e-02,  3.6365e-02,  4.2601e-02,
                         9.5680e-02, -4.4193e-02,  5.1107e-02,  1.9187e-01,  3.5678e-01,
                         6.6560e-02,  8.5484e-03,  2.0514e-02,  2.7039e-02,  6.3104e-02,
                         2.8506e-02, -9.6596e-02,  9.6870e-03,  1.0163e-01,  1.4900e-01,
                         1.1239e-01,  3.5970e-02,  9.4504e-02,  3.3720e-02,  5.9837

In [18]:
path='/home/uzair.khattak/ML_project/ml_project/saved_models/recylce_material512by512'

In [20]:
loaded=model_ft.load_state_dict(torch.load(path))

In [21]:
loaded

<All keys matched successfully>

In [22]:
model_ft

VisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (blocks): Sequential(
    (0): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop): Dropout(p=0.0, inplace=False)
      )
    )
    (1): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn

In [25]:
type(x.to("cuda"))

torch.Tensor

In [26]:
x

tensor([[[[-0.9012,  0.7045,  0.0129,  ..., -0.7987,  1.6578, -0.9922],
          [ 0.3945,  0.7837, -0.1037,  ...,  0.6142,  1.5600,  1.0722],
          [-1.3797, -0.1546,  0.3965,  ...,  1.5019,  0.2018,  0.7390],
          ...,
          [-1.0402, -1.1197, -0.7108,  ..., -1.4976, -0.9763,  0.1614],
          [ 1.0158,  0.9156,  0.9462,  ..., -0.9392,  1.0388, -0.1084],
          [-0.1267, -0.7079, -0.9119,  ...,  0.9749, -1.7909, -1.1995]],

         [[ 1.3343, -0.4062,  0.5811,  ...,  0.3762, -0.5807, -0.9719],
          [-0.0100, -0.5197,  0.9462,  ...,  1.3118,  0.9484, -0.3515],
          [-0.8409,  0.3586, -2.0042,  ..., -0.9038,  0.3094, -0.5757],
          ...,
          [-0.6416,  0.9225,  1.1163,  ..., -0.3202, -0.6624,  0.0357],
          [ 0.0857,  1.8403,  0.3397,  ..., -1.3719,  1.1249,  1.4205],
          [-0.7218, -1.5353, -0.0403,  ...,  0.6264,  0.4344,  0.4651]],

         [[ 0.6633,  0.8232, -1.1577,  ..., -1.1069,  1.5550, -1.3647],
          [-0.6640,  0.2976,  